# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/franc/hydro_spartan_7/hydro_spartan_7.srcs/sources_1/bd/mb_system/ip/mb_system_iomodule_1_0/mb_system_iomodule_1_0.xci
# IP: The module: 'mb_system_iomodule_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/franc/hydro_spartan_7/hydro_spartan_7.srcs/sources_1/bd/mb_system/ip/mb_system_iomodule_1_0/mb_system_iomodule_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_system_iomodule_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/franc/hydro_spartan_7/hydro_spartan_7.srcs/sources_1/bd/mb_system/ip/mb_system_iomodule_1_0/mb_system_iomodule_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_system_iomodule_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/franc/hydro_spartan_7/hydro_spartan_7.srcs/sources_1/bd/mb_system/ip/mb_system_iomodule_1_0/mb_system_iomodule_1_0.xci
# IP: The module: 'mb_system_iomodule_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/franc/hydro_spartan_7/hydro_spartan_7.srcs/sources_1/bd/mb_system/ip/mb_system_iomodule_1_0/mb_system_iomodule_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_system_iomodule_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/franc/hydro_spartan_7/hydro_spartan_7.srcs/sources_1/bd/mb_system/ip/mb_system_iomodule_1_0/mb_system_iomodule_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_system_iomodule_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
