# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/xc7s50_pinout.xdc

# Block Designs: bd/mb_system/mb_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_system || ORIG_REF_NAME==mb_system} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_microblaze_0_2/mb_system_microblaze_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_system_microblaze_0_2 || ORIG_REF_NAME==mb_system_microblaze_0_2} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_dlmb_v10_2/mb_system_dlmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_system_dlmb_v10_2 || ORIG_REF_NAME==mb_system_dlmb_v10_2} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_ilmb_v10_2/mb_system_ilmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_system_ilmb_v10_2 || ORIG_REF_NAME==mb_system_ilmb_v10_2} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_dlmb_bram_if_cntlr_2/mb_system_dlmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_system_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==mb_system_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_ilmb_bram_if_cntlr_2/mb_system_ilmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_system_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==mb_system_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_lmb_bram_2/mb_system_lmb_bram_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_system_lmb_bram_2 || ORIG_REF_NAME==mb_system_lmb_bram_2} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_mdm_1_2/mb_system_mdm_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_system_mdm_1_2 || ORIG_REF_NAME==mb_system_mdm_1_2} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_clk_wiz_1_1/mb_system_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_system_clk_wiz_1_1 || ORIG_REF_NAME==mb_system_clk_wiz_1_1} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_rst_clk_wiz_1_100M_1/mb_system_rst_clk_wiz_1_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_system_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==mb_system_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_axi_uartlite_0_1/mb_system_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_system_axi_uartlite_0_1 || ORIG_REF_NAME==mb_system_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_microblaze_0_axi_periph_2/mb_system_microblaze_0_axi_periph_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_system_microblaze_0_axi_periph_2 || ORIG_REF_NAME==mb_system_microblaze_0_axi_periph_2} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_axi_quad_spi_0_1/mb_system_axi_quad_spi_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_system_axi_quad_spi_0_1 || ORIG_REF_NAME==mb_system_axi_quad_spi_0_1} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_iomodule_1_1/mb_system_iomodule_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_system_iomodule_1_1 || ORIG_REF_NAME==mb_system_iomodule_1_1} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_iomodule_2_1/mb_system_iomodule_2_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_system_iomodule_2_1 || ORIG_REF_NAME==mb_system_iomodule_2_1} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_xbar_0/mb_system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_system_xbar_0 || ORIG_REF_NAME==mb_system_xbar_0} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_clk_wiz_0_0/mb_system_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_system_clk_wiz_0_0 || ORIG_REF_NAME==mb_system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/mb_system/ip/mb_system_iomodule_0_0/mb_system_iomodule_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_system_iomodule_0_0 || ORIG_REF_NAME==mb_system_iomodule_0_0} -quiet] -quiet

# IP: ip/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: bd/mb_system/ip/mb_system_microblaze_0_2/mb_system_microblaze_0_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_microblaze_0_2 || ORIG_REF_NAME==mb_system_microblaze_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_system/ip/mb_system_microblaze_0_2/mb_system_microblaze_0_2_ooc_debug.xdc

# XDC: bd/mb_system/ip/mb_system_dlmb_v10_2/mb_system_dlmb_v10_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_dlmb_v10_2 || ORIG_REF_NAME==mb_system_dlmb_v10_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_system/ip/mb_system_lmb_bram_2/mb_system_lmb_bram_2_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_mdm_1_2/mb_system_mdm_1_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_mdm_1_2 || ORIG_REF_NAME==mb_system_mdm_1_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_system/ip/mb_system_mdm_1_2/mb_system_mdm_1_2_ooc_trace.xdc

# XDC: bd/mb_system/ip/mb_system_clk_wiz_1_1/mb_system_clk_wiz_1_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_clk_wiz_1_1 || ORIG_REF_NAME==mb_system_clk_wiz_1_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_system/ip/mb_system_clk_wiz_1_1/mb_system_clk_wiz_1_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_clk_wiz_1_1 || ORIG_REF_NAME==mb_system_clk_wiz_1_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_system/ip/mb_system_clk_wiz_1_1/mb_system_clk_wiz_1_1_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_rst_clk_wiz_1_100M_1/mb_system_rst_clk_wiz_1_100M_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==mb_system_rst_clk_wiz_1_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_system/ip/mb_system_rst_clk_wiz_1_100M_1/mb_system_rst_clk_wiz_1_100M_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==mb_system_rst_clk_wiz_1_100M_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_system/ip/mb_system_axi_uartlite_0_1/mb_system_axi_uartlite_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_axi_uartlite_0_1 || ORIG_REF_NAME==mb_system_axi_uartlite_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_system/ip/mb_system_axi_uartlite_0_1/mb_system_axi_uartlite_0_1_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_axi_uartlite_0_1/mb_system_axi_uartlite_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_axi_uartlite_0_1 || ORIG_REF_NAME==mb_system_axi_uartlite_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_system/ip/mb_system_axi_quad_spi_0_1/mb_system_axi_quad_spi_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_axi_quad_spi_0_1 || ORIG_REF_NAME==mb_system_axi_quad_spi_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_system/ip/mb_system_axi_quad_spi_0_1/mb_system_axi_quad_spi_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_axi_quad_spi_0_1 || ORIG_REF_NAME==mb_system_axi_quad_spi_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_system/ip/mb_system_axi_quad_spi_0_1/mb_system_axi_quad_spi_0_1_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_axi_quad_spi_0_1/mb_system_axi_quad_spi_0_1_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_axi_quad_spi_0_1 || ORIG_REF_NAME==mb_system_axi_quad_spi_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_system/ip/mb_system_iomodule_1_1/mb_system_iomodule_1_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_iomodule_1_1 || ORIG_REF_NAME==mb_system_iomodule_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_system/ip/mb_system_iomodule_2_1/mb_system_iomodule_2_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_iomodule_2_1 || ORIG_REF_NAME==mb_system_iomodule_2_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_system/ip/mb_system_clk_wiz_0_0/mb_system_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_clk_wiz_0_0 || ORIG_REF_NAME==mb_system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_system/ip/mb_system_clk_wiz_0_0/mb_system_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_clk_wiz_0_0 || ORIG_REF_NAME==mb_system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/mb_system/ip/mb_system_clk_wiz_0_0/mb_system_clk_wiz_0_0_ooc.xdc

# XDC: bd/mb_system/ip/mb_system_iomodule_0_0/mb_system_iomodule_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_system_iomodule_0_0 || ORIG_REF_NAME==mb_system_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/mb_system/mb_system_ooc.xdc

# XDC: ip/fifo_generator_0/fifo_generator_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/fifo_generator_0/fifo_generator_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
