-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj_no_atan\hdlsrc\DOA_rearanged\Fenetrage.vhd
-- Created: 2021-10-12 21:18:51
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Fenetrage
-- Source Path: DOA_rearanged/FFTs/Fenetrage
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.DOA_rearanged_pkg.ALL;

ENTITY Fenetrage IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Canal1                            :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Threshold                         :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        isReady                           :   IN    std_logic;
        Enable                            :   IN    std_logic;
        Coeff                             :   OUT   std_logic_vector(8 DOWNTO 0);  -- ufix9_En8
        Ready                             :   OUT   std_logic
        );
END Fenetrage;


ARCHITECTURE rtl OF Fenetrage IS

  -- Component Declarations
  COMPONENT SampleHold
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Trigger                         :   IN    std_logic;
          In2                             :   IN    std_logic;
          alpha                           :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SampleHold
    USE ENTITY work.SampleHold(rtl);

  -- Constants
  CONSTANT Direct_Lookup_Table_n_D_table_data : vector_of_unsigned9(0 TO 255) := 
    (to_unsigned(16#000#, 9), to_unsigned(16#000#, 9), to_unsigned(16#000#, 9), to_unsigned(16#000#, 9),
     to_unsigned(16#001#, 9), to_unsigned(16#001#, 9), to_unsigned(16#001#, 9), to_unsigned(16#002#, 9),
     to_unsigned(16#002#, 9), to_unsigned(16#003#, 9), to_unsigned(16#004#, 9), to_unsigned(16#005#, 9),
     to_unsigned(16#006#, 9), to_unsigned(16#007#, 9), to_unsigned(16#008#, 9), to_unsigned(16#009#, 9),
     to_unsigned(16#00A#, 9), to_unsigned(16#00B#, 9), to_unsigned(16#00C#, 9), to_unsigned(16#00E#, 9),
     to_unsigned(16#00F#, 9), to_unsigned(16#011#, 9), to_unsigned(16#012#, 9), to_unsigned(16#014#, 9),
     to_unsigned(16#016#, 9), to_unsigned(16#018#, 9), to_unsigned(16#019#, 9), to_unsigned(16#01B#, 9),
     to_unsigned(16#01D#, 9), to_unsigned(16#01F#, 9), to_unsigned(16#021#, 9), to_unsigned(16#024#, 9),
     to_unsigned(16#026#, 9), to_unsigned(16#028#, 9), to_unsigned(16#02A#, 9), to_unsigned(16#02D#, 9),
     to_unsigned(16#02F#, 9), to_unsigned(16#032#, 9), to_unsigned(16#034#, 9), to_unsigned(16#037#, 9),
     to_unsigned(16#039#, 9), to_unsigned(16#03C#, 9), to_unsigned(16#03F#, 9), to_unsigned(16#041#, 9),
     to_unsigned(16#044#, 9), to_unsigned(16#047#, 9), to_unsigned(16#04A#, 9), to_unsigned(16#04D#, 9),
     to_unsigned(16#050#, 9), to_unsigned(16#052#, 9), to_unsigned(16#055#, 9), to_unsigned(16#058#, 9),
     to_unsigned(16#05B#, 9), to_unsigned(16#05E#, 9), to_unsigned(16#062#, 9), to_unsigned(16#065#, 9),
     to_unsigned(16#068#, 9), to_unsigned(16#06B#, 9), to_unsigned(16#06E#, 9), to_unsigned(16#071#, 9),
     to_unsigned(16#074#, 9), to_unsigned(16#077#, 9), to_unsigned(16#07A#, 9), to_unsigned(16#07E#, 9),
     to_unsigned(16#081#, 9), to_unsigned(16#084#, 9), to_unsigned(16#087#, 9), to_unsigned(16#08A#, 9),
     to_unsigned(16#08D#, 9), to_unsigned(16#091#, 9), to_unsigned(16#094#, 9), to_unsigned(16#097#, 9),
     to_unsigned(16#09A#, 9), to_unsigned(16#09D#, 9), to_unsigned(16#0A0#, 9), to_unsigned(16#0A3#, 9),
     to_unsigned(16#0A6#, 9), to_unsigned(16#0A9#, 9), to_unsigned(16#0AC#, 9), to_unsigned(16#0AF#, 9),
     to_unsigned(16#0B2#, 9), to_unsigned(16#0B5#, 9), to_unsigned(16#0B8#, 9), to_unsigned(16#0BA#, 9),
     to_unsigned(16#0BD#, 9), to_unsigned(16#0C0#, 9), to_unsigned(16#0C3#, 9), to_unsigned(16#0C5#, 9),
     to_unsigned(16#0C8#, 9), to_unsigned(16#0CB#, 9), to_unsigned(16#0CD#, 9), to_unsigned(16#0D0#, 9),
     to_unsigned(16#0D2#, 9), to_unsigned(16#0D4#, 9), to_unsigned(16#0D7#, 9), to_unsigned(16#0D9#, 9),
     to_unsigned(16#0DB#, 9), to_unsigned(16#0DE#, 9), to_unsigned(16#0E0#, 9), to_unsigned(16#0E2#, 9),
     to_unsigned(16#0E4#, 9), to_unsigned(16#0E6#, 9), to_unsigned(16#0E8#, 9), to_unsigned(16#0E9#, 9),
     to_unsigned(16#0EB#, 9), to_unsigned(16#0ED#, 9), to_unsigned(16#0EE#, 9), to_unsigned(16#0F0#, 9),
     to_unsigned(16#0F2#, 9), to_unsigned(16#0F3#, 9), to_unsigned(16#0F4#, 9), to_unsigned(16#0F6#, 9),
     to_unsigned(16#0F7#, 9), to_unsigned(16#0F8#, 9), to_unsigned(16#0F9#, 9), to_unsigned(16#0FA#, 9),
     to_unsigned(16#0FB#, 9), to_unsigned(16#0FC#, 9), to_unsigned(16#0FD#, 9), to_unsigned(16#0FD#, 9),
     to_unsigned(16#0FE#, 9), to_unsigned(16#0FE#, 9), to_unsigned(16#0FF#, 9), to_unsigned(16#0FF#, 9),
     to_unsigned(16#100#, 9), to_unsigned(16#100#, 9), to_unsigned(16#100#, 9), to_unsigned(16#100#, 9),
     to_unsigned(16#100#, 9), to_unsigned(16#100#, 9), to_unsigned(16#100#, 9), to_unsigned(16#100#, 9),
     to_unsigned(16#0FF#, 9), to_unsigned(16#0FF#, 9), to_unsigned(16#0FE#, 9), to_unsigned(16#0FE#, 9),
     to_unsigned(16#0FD#, 9), to_unsigned(16#0FD#, 9), to_unsigned(16#0FC#, 9), to_unsigned(16#0FB#, 9),
     to_unsigned(16#0FA#, 9), to_unsigned(16#0F9#, 9), to_unsigned(16#0F8#, 9), to_unsigned(16#0F7#, 9),
     to_unsigned(16#0F6#, 9), to_unsigned(16#0F4#, 9), to_unsigned(16#0F3#, 9), to_unsigned(16#0F2#, 9),
     to_unsigned(16#0F0#, 9), to_unsigned(16#0EE#, 9), to_unsigned(16#0ED#, 9), to_unsigned(16#0EB#, 9),
     to_unsigned(16#0E9#, 9), to_unsigned(16#0E8#, 9), to_unsigned(16#0E6#, 9), to_unsigned(16#0E4#, 9),
     to_unsigned(16#0E2#, 9), to_unsigned(16#0E0#, 9), to_unsigned(16#0DE#, 9), to_unsigned(16#0DB#, 9),
     to_unsigned(16#0D9#, 9), to_unsigned(16#0D7#, 9), to_unsigned(16#0D4#, 9), to_unsigned(16#0D2#, 9),
     to_unsigned(16#0D0#, 9), to_unsigned(16#0CD#, 9), to_unsigned(16#0CB#, 9), to_unsigned(16#0C8#, 9),
     to_unsigned(16#0C5#, 9), to_unsigned(16#0C3#, 9), to_unsigned(16#0C0#, 9), to_unsigned(16#0BD#, 9),
     to_unsigned(16#0BA#, 9), to_unsigned(16#0B8#, 9), to_unsigned(16#0B5#, 9), to_unsigned(16#0B2#, 9),
     to_unsigned(16#0AF#, 9), to_unsigned(16#0AC#, 9), to_unsigned(16#0A9#, 9), to_unsigned(16#0A6#, 9),
     to_unsigned(16#0A3#, 9), to_unsigned(16#0A0#, 9), to_unsigned(16#09D#, 9), to_unsigned(16#09A#, 9),
     to_unsigned(16#097#, 9), to_unsigned(16#094#, 9), to_unsigned(16#091#, 9), to_unsigned(16#08D#, 9),
     to_unsigned(16#08A#, 9), to_unsigned(16#087#, 9), to_unsigned(16#084#, 9), to_unsigned(16#081#, 9),
     to_unsigned(16#07E#, 9), to_unsigned(16#07A#, 9), to_unsigned(16#077#, 9), to_unsigned(16#074#, 9),
     to_unsigned(16#071#, 9), to_unsigned(16#06E#, 9), to_unsigned(16#06B#, 9), to_unsigned(16#068#, 9),
     to_unsigned(16#065#, 9), to_unsigned(16#062#, 9), to_unsigned(16#05E#, 9), to_unsigned(16#05B#, 9),
     to_unsigned(16#058#, 9), to_unsigned(16#055#, 9), to_unsigned(16#052#, 9), to_unsigned(16#050#, 9),
     to_unsigned(16#04D#, 9), to_unsigned(16#04A#, 9), to_unsigned(16#047#, 9), to_unsigned(16#044#, 9),
     to_unsigned(16#041#, 9), to_unsigned(16#03F#, 9), to_unsigned(16#03C#, 9), to_unsigned(16#039#, 9),
     to_unsigned(16#037#, 9), to_unsigned(16#034#, 9), to_unsigned(16#032#, 9), to_unsigned(16#02F#, 9),
     to_unsigned(16#02D#, 9), to_unsigned(16#02A#, 9), to_unsigned(16#028#, 9), to_unsigned(16#026#, 9),
     to_unsigned(16#024#, 9), to_unsigned(16#021#, 9), to_unsigned(16#01F#, 9), to_unsigned(16#01D#, 9),
     to_unsigned(16#01B#, 9), to_unsigned(16#019#, 9), to_unsigned(16#018#, 9), to_unsigned(16#016#, 9),
     to_unsigned(16#014#, 9), to_unsigned(16#012#, 9), to_unsigned(16#011#, 9), to_unsigned(16#00F#, 9),
     to_unsigned(16#00E#, 9), to_unsigned(16#00C#, 9), to_unsigned(16#00B#, 9), to_unsigned(16#00A#, 9),
     to_unsigned(16#009#, 9), to_unsigned(16#008#, 9), to_unsigned(16#007#, 9), to_unsigned(16#006#, 9),
     to_unsigned(16#005#, 9), to_unsigned(16#004#, 9), to_unsigned(16#003#, 9), to_unsigned(16#002#, 9),
     to_unsigned(16#002#, 9), to_unsigned(16#001#, 9), to_unsigned(16#001#, 9), to_unsigned(16#001#, 9),
     to_unsigned(16#000#, 9), to_unsigned(16#000#, 9), to_unsigned(16#000#, 9), to_unsigned(16#000#, 9));  -- ufix9 [256]

  -- Signals
  SIGNAL Canal1_unsigned                  : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Threshold_unsigned               : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Relational_Operator_relop1       : std_logic;
  SIGNAL Logical_Operator1_out1           : std_logic;
  SIGNAL Logical_Operator_out1            : std_logic;
  SIGNAL SampleHold_out1                  : std_logic;
  SIGNAL Constant1_out1                   : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Delay_out1                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add_out1                         : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Compare_To_Constant_out1         : std_logic;
  SIGNAL Logical_Operator3_out1           : std_logic;
  SIGNAL Product4_out1                    : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Constant_out1                    : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Switch_out1                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Direct_Lookup_Table_n_D_out1     : unsigned(8 DOWNTO 0);  -- ufix9_En8
  SIGNAL Logical_Operator2_out1           : std_logic;

BEGIN
  u_SampleHold : SampleHold
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              Trigger => Logical_Operator_out1,
              In2 => isReady,
              alpha => SampleHold_out1
              );

  Canal1_unsigned <= unsigned(Canal1);

  Threshold_unsigned <= unsigned(Threshold);

  
  Relational_Operator_relop1 <= '1' WHEN Canal1_unsigned >= Threshold_unsigned ELSE
      '0';

  Logical_Operator1_out1 <=  NOT isReady;

  Logical_Operator_out1 <= Relational_Operator_relop1 XOR Logical_Operator1_out1;

  Constant1_out1 <= to_unsigned(16#0001#, 16);

  Add_out1 <= Constant1_out1 + Delay_out1;

  
  Compare_To_Constant_out1 <= '1' WHEN Delay_out1 <= to_unsigned(16#0100#, 16) ELSE
      '0';

  Logical_Operator3_out1 <= Compare_To_Constant_out1 AND (SampleHold_out1 AND Enable);

  
  Product4_out1 <= Add_out1 WHEN Logical_Operator3_out1 = '1' ELSE
      to_unsigned(16#0000#, 16);

  Delay_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF reset = '1' THEN
        Delay_out1 <= to_unsigned(16#0000#, 16);
      ELSIF enb = '1' THEN
        Delay_out1 <= Product4_out1;
      END IF;
    END IF;
  END PROCESS Delay_process;


  
  switch_compare_1 <= '1' WHEN Delay_out1 >= to_unsigned(16#0100#, 16) ELSE
      '0';

  Constant_out1 <= to_unsigned(16#0000#, 16);

  
  Switch_out1 <= Delay_out1 WHEN switch_compare_1 = '0' ELSE
      Constant_out1;

  Direct_Lookup_Table_n_D_out1 <= Direct_Lookup_Table_n_D_table_data(to_integer(Switch_out1));

  Coeff <= std_logic_vector(Direct_Lookup_Table_n_D_out1);

  Logical_Operator2_out1 <= SampleHold_out1 AND Enable;

  Ready <= Logical_Operator2_out1;

END rtl;

