-- -------------------------------------------------------------
-- 
-- File Name: test_enable_change\hdlsrc\Test_DOA\FFTs.vhd
-- Created: 2021-10-20 16:31:19
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: FFTs
-- Source Path: Test_DOA/FFTs
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY FFTs IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Canal1                            :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Canal2                            :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Canal3                            :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Canal4                            :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Enable                            :   IN    std_logic;
        Signal_Threshold                  :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Magnitude_Ref                     :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En8
        Phase_Ref                         :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
        Valid_out_Ref                     :   OUT   std_logic;
        Magnitude1                        :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En8
        Phase1                            :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
        Valid_out1                        :   OUT   std_logic;
        Magnitude2                        :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En8
        Phase2                            :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
        Valid_out2                        :   OUT   std_logic;
        Magnitude3                        :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En8
        Phase3                            :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
        Valid_out3                        :   OUT   std_logic
        );
END FFTs;


ARCHITECTURE rtl OF FFTs IS

  -- Component Declarations
  COMPONENT Fenetrage
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Canal1                          :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          Threshold                       :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          isReady                         :   IN    std_logic;
          Enable                          :   IN    std_logic;
          Coeff                           :   OUT   std_logic_vector(8 DOWNTO 0);  -- ufix9_En8
          Ready                           :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT FFT_Hydro_Ref
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Data                            :   IN    std_logic_vector(24 DOWNTO 0);  -- ufix25_En8
          ValidIn                         :   IN    std_logic;
          Magnitude                       :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En8
          Angle                           :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
          Valid                           :   OUT   std_logic;
          Ready                           :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT FFT_Hydro_1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Data                            :   IN    std_logic_vector(24 DOWNTO 0);  -- ufix25_En8
          Valid_in                        :   IN    std_logic;
          Magnitude                       :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En8
          Phase                           :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
          Valid_out                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT FFT_Hydro_2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Data                            :   IN    std_logic_vector(24 DOWNTO 0);  -- ufix25_En8
          Valid_in                        :   IN    std_logic;
          Magnitude                       :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En8
          Phase                           :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
          Valid_out                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT FFT_Hydro_3
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Data                            :   IN    std_logic_vector(24 DOWNTO 0);  -- ufix25_En8
          Valid_in                        :   IN    std_logic;
          Magnitude                       :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En8
          Phase                           :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
          Valid_out                       :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Fenetrage
    USE ENTITY work.Fenetrage(rtl);

  FOR ALL : FFT_Hydro_Ref
    USE ENTITY work.FFT_Hydro_Ref(rtl);

  FOR ALL : FFT_Hydro_1
    USE ENTITY work.FFT_Hydro_1(rtl);

  FOR ALL : FFT_Hydro_2
    USE ENTITY work.FFT_Hydro_2(rtl);

  FOR ALL : FFT_Hydro_3
    USE ENTITY work.FFT_Hydro_3(rtl);

  -- Signals
  SIGNAL Canal1_unsigned                  : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL FFT_Hydro_Ref_out4               : std_logic;
  SIGNAL Fenetrage_out1                   : std_logic_vector(8 DOWNTO 0);  -- ufix9
  SIGNAL Fenetrage_out2                   : std_logic;
  SIGNAL Fenetrage_out1_unsigned          : unsigned(8 DOWNTO 0);  -- ufix9_En8
  SIGNAL Product3_out1                    : unsigned(24 DOWNTO 0);  -- ufix25_En8
  SIGNAL FFT_Hydro_Ref_out1               : std_logic_vector(26 DOWNTO 0);  -- ufix27
  SIGNAL FFT_Hydro_Ref_out2               : std_logic_vector(28 DOWNTO 0);  -- ufix29
  SIGNAL FFT_Hydro_Ref_out3               : std_logic;
  SIGNAL Canal2_unsigned                  : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Product_out1                     : unsigned(24 DOWNTO 0);  -- ufix25_En8
  SIGNAL FFT_Hydro_1_out1                 : std_logic_vector(26 DOWNTO 0);  -- ufix27
  SIGNAL FFT_Hydro_1_out2                 : std_logic_vector(28 DOWNTO 0);  -- ufix29
  SIGNAL FFT_Hydro_1_out3                 : std_logic;
  SIGNAL Canal3_unsigned                  : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Product1_out1                    : unsigned(24 DOWNTO 0);  -- ufix25_En8
  SIGNAL FFT_Hydro_2_out1                 : std_logic_vector(26 DOWNTO 0);  -- ufix27
  SIGNAL FFT_Hydro_2_out2                 : std_logic_vector(28 DOWNTO 0);  -- ufix29
  SIGNAL FFT_Hydro_2_out3                 : std_logic;
  SIGNAL Canal4_unsigned                  : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Product2_out1                    : unsigned(24 DOWNTO 0);  -- ufix25_En8
  SIGNAL FFT_Hydro_3_out1                 : std_logic_vector(26 DOWNTO 0);  -- ufix27
  SIGNAL FFT_Hydro_3_out2                 : std_logic_vector(28 DOWNTO 0);  -- ufix29
  SIGNAL FFT_Hydro_3_out3                 : std_logic;

BEGIN
  u_Fenetrage : Fenetrage
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              Canal1 => Canal1,  -- uint16
              Threshold => Signal_Threshold,  -- uint16
              isReady => FFT_Hydro_Ref_out4,
              Enable => Enable,
              Coeff => Fenetrage_out1,  -- ufix9_En8
              Ready => Fenetrage_out2
              );

  u_FFT_Hydro_Ref : FFT_Hydro_Ref
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              Data => std_logic_vector(Product3_out1),  -- ufix25_En8
              ValidIn => Fenetrage_out2,
              Magnitude => FFT_Hydro_Ref_out1,  -- sfix27_En8
              Angle => FFT_Hydro_Ref_out2,  -- sfix29_En26
              Valid => FFT_Hydro_Ref_out3,
              Ready => FFT_Hydro_Ref_out4
              );

  u_FFT_Hydro_1 : FFT_Hydro_1
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              Data => std_logic_vector(Product_out1),  -- ufix25_En8
              Valid_in => Fenetrage_out2,
              Magnitude => FFT_Hydro_1_out1,  -- sfix27_En8
              Phase => FFT_Hydro_1_out2,  -- sfix29_En26
              Valid_out => FFT_Hydro_1_out3
              );

  u_FFT_Hydro_2 : FFT_Hydro_2
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              Data => std_logic_vector(Product1_out1),  -- ufix25_En8
              Valid_in => Fenetrage_out2,
              Magnitude => FFT_Hydro_2_out1,  -- sfix27_En8
              Phase => FFT_Hydro_2_out2,  -- sfix29_En26
              Valid_out => FFT_Hydro_2_out3
              );

  u_FFT_Hydro_3 : FFT_Hydro_3
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              Data => std_logic_vector(Product2_out1),  -- ufix25_En8
              Valid_in => Fenetrage_out2,
              Magnitude => FFT_Hydro_3_out1,  -- sfix27_En8
              Phase => FFT_Hydro_3_out2,  -- sfix29_En26
              Valid_out => FFT_Hydro_3_out3
              );

  Canal1_unsigned <= unsigned(Canal1);

  Fenetrage_out1_unsigned <= unsigned(Fenetrage_out1);

  Product3_out1 <= Canal1_unsigned * Fenetrage_out1_unsigned;

  Canal2_unsigned <= unsigned(Canal2);

  Product_out1 <= Fenetrage_out1_unsigned * Canal2_unsigned;

  Canal3_unsigned <= unsigned(Canal3);

  Product1_out1 <= Fenetrage_out1_unsigned * Canal3_unsigned;

  Canal4_unsigned <= unsigned(Canal4);

  Product2_out1 <= Fenetrage_out1_unsigned * Canal4_unsigned;

  Magnitude_Ref <= FFT_Hydro_Ref_out1;

  Phase_Ref <= FFT_Hydro_Ref_out2;

  Valid_out_Ref <= FFT_Hydro_Ref_out3;

  Magnitude1 <= FFT_Hydro_1_out1;

  Phase1 <= FFT_Hydro_1_out2;

  Valid_out1 <= FFT_Hydro_1_out3;

  Magnitude2 <= FFT_Hydro_2_out1;

  Phase2 <= FFT_Hydro_2_out2;

  Valid_out2 <= FFT_Hydro_2_out3;

  Magnitude3 <= FFT_Hydro_3_out1;

  Phase3 <= FFT_Hydro_3_out2;

  Valid_out3 <= FFT_Hydro_3_out3;

END rtl;

