-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj_no_atan\hdlsrc\DOA_rearanged\SampleHold5.vhd
-- Created: 2021-10-12 21:18:51
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: SampleHold5
-- Source Path: DOA_rearanged/Maximum Hydro 1/SampleHold5
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY SampleHold5 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Trigger                           :   IN    std_logic;
        In2                               :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
        alpha                             :   OUT   std_logic_vector(28 DOWNTO 0)  -- sfix29_En26
        );
END SampleHold5;


ARCHITECTURE rtl OF SampleHold5 IS

  -- Component Declarations
  COMPONENT Sample_and_Hold_block1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In_rsvd                         :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
          Trigger                         :   IN    std_logic;
          alpha                           :   OUT   std_logic_vector(28 DOWNTO 0)  -- sfix29_En26
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Sample_and_Hold_block1
    USE ENTITY work.Sample_and_Hold_block1(rtl);

  -- Signals
  SIGNAL Sample_and_Hold_out1             : std_logic_vector(28 DOWNTO 0);  -- ufix29

BEGIN
  u_Sample_and_Hold : Sample_and_Hold_block1
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              In_rsvd => In2,  -- sfix29_En26
              Trigger => Trigger,
              alpha => Sample_and_Hold_out1  -- sfix29_En26
              );

  alpha <= Sample_and_Hold_out1;

END rtl;

